version: 2.1
orbs:
  commitlint: conventional-changelog/commitlint@1.0.0
  node: circleci/node@5.1.0
alias:
  - &defaults
    docker:
      - image: cimg/node:lts
    executor: node/default
jobs:
  branch-job:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages
      - run: npm test
  main-job:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages
      - run: npm test
      - run: npx semantic-release
workflows:
  version: 2
  commitlint:
    jobs:
      - commitlint/lint:
          target-branch: main
  branch-workflow:
    jobs:
      - branch-job:
          filters:
            branches:
              ignore:
                - main
  main-workflow:
    jobs:
      - main-job:
          context:
            - scratch-npm-creds
          filters:
            branches:
              only:
                - main
